apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-stable
  namespace: microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
      track: stable
  template:
    metadata:
      labels:
        app: accounts
        track: stable
        version: v1
    spec:
      containers:
        - name: accounts
          image: ghcr.io/garridoandreag/microservicepy:v1
          imagePullPolicy: Always
          env:
            - name: APP_VERSION
              value: "v1"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10