apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice
      version: stable
  template:
    metadata:
      labels:
        app: microservice
        version: stable
    spec:
      containers:
        - name: microservice
          image: ghcr.io/garridoandreag/microservicepy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
