apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
      track: canary
  template:
    metadata:
      labels:
        app: accounts
        track: canary
    spec:
      containers:
      - name: accounts
        image: ghcr.io/garridoandreag/microservicepy:latest
        ports:
        - containerPort: 8000