apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
      track: stable
  template:
    metadata:
      labels:
        app: accounts
        track: stable
    spec:
      containers:
      - name: accounts
        image: ghcr.io/garridoandreag/microservicepy:latest
        ports:
        - containerPort: 8000