apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
      version: v2
  template:
    metadata:
      labels:
        app: microservice
        version: v2
    spec:
      containers:
      - name: microservice
        image: ghcr.io/garridoandreag/microservicepy:dcba7ee7bb4e57f3b1855518d6173d0f1fba6405
        ports:
          - containerPort: 8000