apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
      version: canary
  template:
    metadata:
      labels:
        app: microservice
        version: canary
    spec:
      containers:
        - name: microservice
          image: ghcr.io/garridoandreag/microservicepy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000